### PR TITLE
Improve ListItemProperty

### PR DESCRIPTION
**Pull request by kirelagin**
These changes do some minor improvements to `ListItemProperty`
and also let the user find out current index of the item tracked.

### CODE REVIEW

**Comment by solomatov** [comment]
We use my prefix for fields. Also, we use only @Nullable annotation and not @NotNull. I merge it in, and make this fixes myself to save time but please make code conform to the code style next time.

**Comment by kirelagin** [comment]
Ok. I just notices another issue: I specified `version` on the dependency in `pom.xml` which should not be done. Could you please remove it too?

**Comment by kirelagin** [comment]
> Also, we use only @Nullable annotation and not @NotNull

Sorry, I didn’t know that. There are a bunch of `@Nonnull` in all the repositories that we use, so I thought that was acceptable.

**Comment by kirelagin** [comment]
And since you removed all the `@Nonnull`, the dependency on `findbugs` should probably be dropped too as it was needed only for this annotation to work.

**Pull request merged**
