### PR TITLE
Refactor edts

### PR DESCRIPTION
**Pull request by katepol**

### CODE REVIEW

**Comment by katepol** [comment]
There are corresponding changes to other repos, so please if you decide to merge this, ping me so that I get ready to push them.

**Comment by solomatov** [comment]
* Finals aren't always unnecessary. They prevent people from overriding specified methods. 
* Also, please don't use millis suffix. In java time is always specified in milliseconds.

Also, this commits breaks complication, so I can't accept it.

**Comment by katepol** [comment]
1) what finals exactly do you mean? if at RunningEdtManager, it's because this class isn't final itself;
2) ok;
3) did you mean 'compilation'? any commit of this kind will break it.

**Comment by solomatov** [comment]
1) agree.

3). compilation of course. Not any commit of this kind will break it. You can find ways to commit such changes without breaking compilation (tip, create a method with the right name in the class where the compilation error appears)

**Pull request closed without merging**
