### PR TITLE
ObservableCollections select and selectList methods

### PR DESCRIPTION
**Pull request by CheatEx**
Fixed #29 
 
 * Updated Listeners implementation to simplify listeners presence/absence tracking
 * Get rid of old tracking via Registration wrapping
 * Abstract base class for derived collections
 * Selector-based derived collections

### CODE REVIEW

**Comment by solomatov** [comment]
It would be nice to have a test for the new functionality for Listeneres

**Comment by solomatov** [comment]
Nice to clear listeners in CompositeEventSource on the last item remove as you do in other places

**Comment by solomatov** [comment]
In SelectorDerivedCollection you use deprecated getItem() method

**Comment by solomatov** [comment]
I think the follow method in DerivedCollection should return a Registration and there should be a way to dispose the collection. What happens if we remove the last listener from the derived collection? I think, we will still have a listener to the collection which we follow, which is an obvious memory leak.

**Comment by solomatov** [comment]
Before you fix the last issue, I can't merge this into the repo.

**Comment by CheatEx** [comment]
* Changed CompositeEventSource to lazily init and remove listeners
* Switched to getOld/New for item access
* Re-written DerivedCollection so all registrations are now maintained privately.

I'm not sure what did you mean by "we will still have a listener to the collection which we follow". Isn't it the case covered by the SelectTest#listRegistrations/collectionRegistrations tests?

Could you reopen this request? It's inconvenient to create a new request for every review iteration. We loose the entire discussion and pollute the repository with duplicating requests.

**Comment by solomatov** [comment]
Ok I will reopen it.

**Comment by solomatov** [comment]
Additional comments:
1. Please don't use names like this: propertyLsnrs, myScrListRegistration In Java it should be called propertyListeners, mySourceRegistration.
2. BTW, what's the reason to use AtomicInteger in tests. This class is for concurrency, and we have no concurrency.
3. You have protected fields in DerivedCollection. Please, get rid of them.


4.
>I'm not sure what did you mean by "we will still have a listener to the collection which we follow". Isn't it the case covered by the SelectTest#listRegistrations/collectionRegistrations tests?

Actually I found out how you check this. You assign to a protected field. The method follow has a counterintuitive contract of assigning to the protected registration field. I can't accept a change with such an architectural problem.

**Comment by CheatEx** [comment]
1. I changed field names but I wasn't able to find anything about abbreviations in our style guide. Kept local variables as is. It looks a little overkill to have a 18 characters long name for a 8 lines long scope and our guide explicitly says so "When you create a local variable, try to use short names, i.e. use i instead of index, etc".
2. I can think of alternative solution with the Value class, but the code would look like count.set(count.get() - 1)
3. I can't find any protected fields in DerivedCollection.
4. See 3.

**Comment by CheatEx** [comment]
3,4 It was my fault - I pushed changes to a wrong branch. Check the DerivedCollection class now.

**Comment by solomatov** [comment]
I think, you should squash review notes into one commit with the initial one.

**Comment by solomatov** [comment]
The following comment is redundant:   // The following methods are intended for implementation of derived lists, similar to DerivedProperty.

**Comment by solomatov** [comment]
Also, the code which you committed is uncompilable which is very sad.

**Comment by solomatov** [comment]
Otherwise everything looks fine. Please, fix these problems and I will merge it in.

**Comment by CheatEx** [comment]
Squashing commits would require a new pull request, github wouldn't allow pull after history rewrite. Is it ok?

I just got 'mvn clean install' successful. What error do you see?

**Comment by solomatov** [comment]
Yes, you should create a new pull request.
I have errors in the Properties class.

**Pull request closed without merging**
