### PR TITLE
(exercise) remove duplication (CompositesBetweenTest)

### PR DESCRIPTION
**Pull request by timzam**

### CODE REVIEW

**Comment by solomatov** [comment]
I don't like numbered test names

**Comment by timzam** [comment]
It's about having one assert per test. We can remove all other tests (tests 2 and higher). Or the author can name the reason for having all those other tests.

**Comment by timzam** [comment]
They are kind of numbered implicitly in the original tests. They can certainly fail independently and we won't know if all of them failed or just one.

**Comment by solomatov** [comment]
I like the solution, but it would be better if we have some more descriptive names. If you finds one, then it's an ideal solution.

**Comment by timzam** [comment]
I submitted the PR with more meaningful names:
https://github.com/JetBrains/jetpad-mapper/pull/187
Closing this one.

**Pull request closed without merging**
